/** @file */
#ifndef CONSTANTS
#define CONSTANTS

#define TILES_HORIZ (int)(SCREEN_WIDTH/TILE_SIZE)
#define TILES_VERT (int)(SCREEN_HEIGHT/TILE_SIZE)
#define STATUSBAR_HEIGHT 16

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define TILE_SIZE 32

#define LEVEL_TIME 20
#define GEM_SCORE_BASE 10
#define SCORE_DIGITS 9

#define BOULDERS_BASE 40
#define BOULDERS_PER_LEVEL 5
#define LAVA_BASE 1
#define LAVA_PER_LEVEL 1
#define GEMS_AMOUNT 10

#endif
