#ifndef CONSTANTS
#define CONSTANTS

#define SCREEN_WIDTH  900
#define SCREEN_HEIGHT 800

#define GAME_WIDTH 700
#define SIDEBAR_WIDTH 200

#define ENEMY_MAX_HEIGHT 700

#define START_HEALTH 3
#define SCORE_DIGITS 9

#define IMMORTAL_TIME 3

#define FIRST_BOSS_SCORE 150
#define BOSS_BAR_HEIGHT 20

#define ENEMY_SPEED 200
#define NEXT_ENEMY_SPAWN_SCORE 50.0
#define ENEMY_SPAWN_COOLDOWN 1

#define POWER_UP_COOLDOWN 5
#define POWER_UP_MIN_SPEED 100
#define POWER_UP_MAX_SPEED 300
#endif
